language: node_js
sudo: false
node_js:
- 7
env:
  global:
  - SAUCE_USERNAME=frypan-knockout-grid
  - secure: lwa7q1/Qck7+bBvwvrthPEJwAiED1B84GT2ziIHtBwJ8MOn0b/nhLX2ysrTL1J5+FB9XpKJoGrZrhN4yUQfRs+2XWNWE6y+FLgRjYJEeVs3rLsu5NLVktmSbF6vCKr7Jnfaifz+lUpqyG7GUeCQ1Ok574PlPOofecEnEEtJ5Uapsty8fUzUBZbc301vZP3Gd6GIVr1lSoIJhRp2hZPkEwv5ohpP9TFECaFlwgSiVvoYZLB4dwCEAVZXEKSw22w7RLTbxU1J5/FBfTl8NLW/QptzekQKuhzcxC6EqtY3t4Us8uBfljEi51jQz5WodwrhiAC09raGZuWMjlhLMVQ3mzmM41zxOq6EUaDcKWuflyKakUy6eJVT+9rDV243kdJ/PiVsZoOUtcSKMlg8S4N72S/GEy7ZDdFu0lj7pzUOoO6cXtLwnccDDWQsynAB7PF1J0miehMQzUUFIe16vKEuJZ54TCs8ldHkdZqhrKgCJb/HkbsIor4nQ72oh9z6zJplbbK0SHdqOTAeXC83mBjuWFqEgPSvj3J85M6yy/a6rPJAV38+dgvZdi/IEs2oagC52PUIsAhZoMNwyIv4NVLdQ/Td3McB7SG4SwlS1VzMXkj2WUE5lnBF0g+pM33gQTmsi7lhvYzhJVHVxCKG30XfAK7/xycLqPfw2kaH5yLm4HXQ=

script: npm test
